//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class escuelaEntities1 : DbContext
    {
        public escuelaEntities1()
            : base("name=escuelaEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<asignatura> asignatura { get; set; }
        public virtual DbSet<carrera> carrera { get; set; }
        public virtual DbSet<docente> docente { get; set; }
        public virtual DbSet<estudiante> estudiante { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
